keys:
  - &user_mahtaran C7FFB72E0527423AD470E132AA82C4EBCB1682E0
  - &host_feanor age1m3fvful26zmrymxpv69ms2jj7cr4yksk65s2yg54sn5ehr9gp52s64tzcz
creation_rules:
  - path_regex: secret/user/mahtaran/[^/]+\.yaml$
    key_groups:
    - pgp:
      - *user_mahtaran
  - path_regex: secret/host/feanor/[^/]+\.yaml$
    key_groups:
    - age:
      - *host_feanor
  - path_regex: secret/[^/]+\.yaml$
    key_groups:
    - pgp:
      - *user_mahtaran
      age:
      - *host_feanor
