keys:
  - &user_mahtaran C7FFB72E0527423AD470E132AA82C4EBCB1682E0
  - &host_feanor age1yawte8ds4r2egs857364g9nqf3lptye7gjhlrl4sfzczv9fghgmq6hyaqj
creation_rules:
  - path_regex: secret/user/mahtaran/.+\.yaml$
    key_groups:
    - pgp:
      - *user_mahtaran
  - path_regex: secret/host/feanor/.+\.yaml$
    key_groups:
    - age:
      - *host_feanor
